from PIL import Image, ImageDraw, ImageFont
from dataclasses import dataclass
from math import ceil
from io import BytesIO


@dataclass
class DifficultyCategory:
    difficulty: int
    ap_count: int
    fc_count: int
    clear_count: int
    all_count: int


data = [
    DifficultyCategory(25, 1, 1, 1, 1),
    DifficultyCategory(26, 26, 26, 26, 26),
    DifficultyCategory(27, 12, 13, 14, 40),
    DifficultyCategory(28, 16, 18, 22, 58),
    DifficultyCategory(29, 25, 52, 52, 52),
    DifficultyCategory(30, 28, 34, 34, 37),
    DifficultyCategory(31, 17, 26, 27, 27),
    DifficultyCategory(32, 0, 12, 15, 15),
    DifficultyCategory(33, 0, 1, 2, 2),
    DifficultyCategory(34, 0, 0, 4, 4),
    DifficultyCategory(35, 0, 0, 2, 2),
    DifficultyCategory(36, 0, 0, 2, 2),
    DifficultyCategory(37, 0, 0, 1, 1),
]


def generate_progress(data: list, difficulty: str):
    FONTPATH = "DATA/data/ASSETS/rodinntlg_eb.otf"
    FONTPATH_LIGHT = "DATA/data/ASSETS/rodinntlg_m.otf"

    IMAGE_WIDTH = 2000
    HEADER_HEIGHT = 200
    SUB_HEADER_HEIGHT = 100
    CARD_HEIGHT = 400
    CARD_GUTTER_HEIGHT = 50
    CARD_GUTTER_WIDTH = 50
    CARD_WIDTH = (IMAGE_WIDTH - (CARD_GUTTER_WIDTH * 3)) // 2
    CARD_RADIUS = 25

    # relative to the card
    CIRCLE_RADIUS = 70
    CIRCLE_X = CIRCLE_RADIUS  # the center of the circle
    CIRCLE_Y = CARD_HEIGHT // 2
    CIRCLE_DIAMETER = CIRCLE_RADIUS * 2

    CIRCLE_TEXT_OFFSET_X = 1.3
    CIRCLE_TEXT_OFFSET_Y = 1.74
    CIRCLE_FONTSIZE = 75
    CIRCLE_FONT = ImageFont.truetype(FONTPATH, CIRCLE_FONTSIZE)

    CIRCLE_TEXT_COLOR = "black"

    DONUT_THICKNESS = 75
    DONUT_PADDING = 30

    FC_COLOR = "#e83ce3"
    CLEAR_COLOR = "#F9D442"
    NOT_CLEAR_COLOR = "#38383a"

    ALL_AP_ICON = "DATA/data/ASSETS/normal_ap.png"
    ALL_FC_ICON = "DATA/data/ASSETS/normal_fc.png"
    ICON_PADDING = 20

    BACKGROUND_IMG = "DATA/data/ASSETS/hug.png"

    COUNT_PADDING_Y = 47
    COUNT_PADDING_X = 30
    COUNT_SPACING = 85
    COUNT_BACKGROUND_COLOR = "#38383adf"
    COUNT_FONTSIZE = 50
    COUNT_FONT_CATEGORIES = ImageFont.truetype(FONTPATH, COUNT_FONTSIZE)

    COUNT_FONT_COLOR = "white"
    COUNT_FONT_TEXT = ImageFont.truetype(FONTPATH_LIGHT, COUNT_FONTSIZE)

    difficulty_colors = {
        "append": "DATA/data/ASSETS/append_color.jpg",
        "hard": "DATA/data/ASSETS/hard_color.jpg",
        "normal": "DATA/data/ASSETS/normal_color.jpg",
        "easy": "DATA/data/ASSETS/easy_color.jpg",
        "master": "DATA/data/ASSETS/master_color.jpg",
        "expert": "DATA/data/ASSETS/expert_color.jpg",
    }

    difficulty_images = {
        key: Image.open(path)
        .resize((CARD_WIDTH, CARD_HEIGHT), Image.LANCZOS)
        .convert("RGBA")
        for key, path in difficulty_colors.items()
    }

    def main(data: list[DifficultyCategory]):
        number_of_cards = len(data)
        # two cards per row
        number_of_rows = ceil(number_of_cards / 2)
        total_height = (
            HEADER_HEIGHT
            + SUB_HEADER_HEIGHT
            + (number_of_rows * CARD_HEIGHT)
            + ((number_of_rows + 1) * CARD_GUTTER_HEIGHT)
        )

        new_im = Image.new("RGBA", (IMAGE_WIDTH, total_height))

        # draw background image
        background_img = Image.open(BACKGROUND_IMG)
        original_width, original_height = background_img.size
        if original_height > total_height:
            background_img = background_img.crop((0, 0, original_width, total_height))
        else:
            background_img = background_img.resize((original_width, total_height))

        background_img = background_img.resize((IMAGE_WIDTH, total_height))
        new_im.paste(background_img, (0, 0))

        im_draw = ImageDraw.Draw(new_im)

        # Top bar
        im_draw.rectangle(
            [(0, 0), (new_im.width, HEADER_HEIGHT)], fill="#b4ccfa", outline="#00194a"
        )

        # Top-left text
        font = ImageFont.truetype(FONTPATH, 96)
        im_draw.text((20, 28), "Your PJSK Progress", fill="black", font=font)
        watermark = ImageFont.truetype(FONTPATH, 60)
        im_draw.text((20, 130), "Generated by Sbotga", fill="black", font=watermark)

        right_text = difficulty.upper()
        right_text_width = font.getlength(right_text)

        image_width, image_height = im_draw.im.size
        x_position = int(image_width - right_text_width - 20)

        def draw_gradient(img, start, end):
            px = img.load()
            for y in range(0, img.height):
                color = tuple(
                    int(start[i] + (end[i] - start[i]) * y / img.height)
                    for i in range(3)
                )
                for x in range(0, img.width):
                    px[x, y] = color

        difficulty_img = difficulty_images[difficulty]
        top_left_color = difficulty_img.getpixel((1, 1))
        bottom_right_color = difficulty_img.getpixel((CARD_WIDTH - 1, CARD_HEIGHT - 1))
        w, h = font.getbbox(right_text)[2:]
        gradient = Image.new("RGB", (w, h))
        draw_gradient(gradient, top_left_color, bottom_right_color)
        im_text = Image.new("RGBA", (w, h))
        d = ImageDraw.Draw(im_text)
        d.text((0, 0), right_text, font=font)
        new_im.paste(gradient, (x_position, 53), im_text)

        for i, diff in enumerate(data):
            data_img = Image.new(
                "RGBA", (CARD_WIDTH, CARD_HEIGHT), color=(255, 255, 255, 0)
            )
            draw = ImageDraw.Draw(data_img)

            # card rectangle
            draw.rounded_rectangle(
                (CIRCLE_RADIUS, 0, CARD_WIDTH, CARD_HEIGHT), radius=25, fill="white"
            )

            # circle with text in the middle
            gradient = Image.new("RGB", (CIRCLE_RADIUS * 2, CIRCLE_RADIUS * 2))
            draw_gradient(gradient, top_left_color, bottom_right_color)
            im_mask = Image.new("L", (CIRCLE_RADIUS * 2, CIRCLE_RADIUS * 2), 0)
            d_mask = ImageDraw.Draw(im_mask)
            d_mask.ellipse((0, 0, CIRCLE_RADIUS * 2, CIRCLE_RADIUS * 2), fill=255)

            ellipse_gradient = Image.composite(
                gradient,
                Image.new("RGB", (CIRCLE_RADIUS * 2, CIRCLE_RADIUS * 2), (0, 0, 0)),
                im_mask,
            )

            data_img.paste(
                ellipse_gradient,
                (CIRCLE_X - CIRCLE_RADIUS, CIRCLE_Y - CIRCLE_RADIUS),
                im_mask,
            )

            draw.text(
                (
                    CIRCLE_X
                    - (CIRCLE_RADIUS / CIRCLE_TEXT_OFFSET_X)
                    + (2 if len(str(diff.difficulty)) == 2 else 28),
                    CIRCLE_Y - (CIRCLE_RADIUS / CIRCLE_TEXT_OFFSET_Y) + 4,
                ),
                str(diff.difficulty),
                fill=CIRCLE_TEXT_COLOR,
                font=CIRCLE_FONT,
            )

            # donut chart
            donut_width = CARD_HEIGHT - (DONUT_PADDING * 2)
            donut_img = Image.new(
                "RGBA", (donut_width, donut_width), color=(255, 255, 255, 0)
            )

            # draw pie chart
            aped = diff.ap_count
            fced = diff.fc_count - diff.ap_count
            cleared = diff.clear_count - diff.fc_count
            not_cleared = diff.all_count - diff.clear_count

            percentage_ap = aped / diff.all_count
            percentage_fc = fced / diff.all_count
            percentage_clear = cleared / diff.all_count
            percentage_not_clear = not_cleared / diff.all_count

            angle_ap = percentage_ap * 360
            angle_fc = angle_ap + (percentage_fc * 360)
            angle_clear = angle_fc + (percentage_clear * 360)
            angle_not_clear = angle_clear + (percentage_not_clear * 360)

            donut_draw = ImageDraw.Draw(donut_img)
            pie_location = (0, 0, donut_width, donut_width)
            donut_draw.pieslice(pie_location, 0, 360, fill="white")

            ap_color_sample = Image.open(ALL_AP_ICON)

            # Get the top and bottom colors
            color_top = ap_color_sample.getpixel((ap_color_sample.size[0] // 2, 60))
            color_bottom = ap_color_sample.getpixel(
                (ap_color_sample.size[0] // 2, ap_color_sample.size[1] - 60)
            )

            gradient = Image.new("RGB", (donut_width, donut_width))
            draw_gradient(gradient, color_top, color_bottom)

            # Create the mask for the pie slice
            im_mask = Image.new(
                "L", (donut_width, donut_width), 0
            )  # Single-channel (grayscale) mask
            d_mask = ImageDraw.Draw(im_mask)
            d_mask.pieslice(
                (0, 0, donut_width, donut_width), 0, angle_ap, fill=255
            )  # Fill the slice with white
            # Paste the gradient onto the donut image using the mask
            donut_img.paste(gradient, pie_location[:2], im_mask)

            donut_draw.pieslice(pie_location, angle_ap, angle_fc, fill=FC_COLOR)
            donut_draw.pieslice(pie_location, angle_fc, angle_clear, fill=CLEAR_COLOR)
            donut_draw.pieslice(
                pie_location, angle_clear, angle_not_clear, fill=NOT_CLEAR_COLOR
            )

            # erase the middle to make it a donut
            donut_draw.ellipse(
                (
                    DONUT_THICKNESS,
                    DONUT_THICKNESS,
                    CARD_HEIGHT - DONUT_THICKNESS - (DONUT_PADDING * 2),
                    CARD_HEIGHT - DONUT_THICKNESS - (DONUT_PADDING * 2),
                ),
                fill="white",
            )

            # if it's all APed or all FCed, draw icon in the middle
            icon_size = (
                donut_width
                - (DONUT_THICKNESS * 2)
                - (DONUT_PADDING * 2)
                - (ICON_PADDING * 2)
            )
            icon_x = (donut_width - icon_size) // 2
            icon_y = (donut_width - icon_size) // 2
            if diff.ap_count == diff.all_count:
                all_ap_img = Image.open(ALL_AP_ICON)
                all_ap_img = all_ap_img.resize((icon_size, icon_size))
                donut_img.paste(all_ap_img, (icon_x, icon_y), all_ap_img)
            elif diff.fc_count == diff.all_count:
                all_fc_img = Image.open(ALL_FC_ICON)
                all_fc_img = all_fc_img.resize((icon_size, icon_size))
                donut_img.paste(all_fc_img, (icon_x, icon_y), all_fc_img)

            data_img.paste(
                donut_img,
                ((CIRCLE_RADIUS * 2) + DONUT_PADDING, DONUT_PADDING),
                donut_img,
            )

            # counts in the right
            count_width = (
                CARD_WIDTH - (CIRCLE_RADIUS * 2) - donut_width - DONUT_PADDING * 2
            )
            count_img = Image.new(
                "RGBA", (count_width, CARD_HEIGHT), color=(255, 255, 255, 0)
            )
            count_draw = ImageDraw.Draw(count_img)
            # only round the right side
            count_draw.rounded_rectangle(
                (0, 0, count_width, CARD_HEIGHT), radius=25, fill=COUNT_BACKGROUND_COLOR
            )
            count_draw.rectangle(
                (0, 0, count_width / 2, CARD_HEIGHT), fill=COUNT_BACKGROUND_COLOR
            )

            ap_pos = (COUNT_PADDING_X, COUNT_PADDING_Y)
            fc_pos = (COUNT_PADDING_X, COUNT_PADDING_Y + COUNT_SPACING)
            clear_pos = (COUNT_PADDING_X, COUNT_PADDING_Y + COUNT_SPACING * 2)
            all_pos = (COUNT_PADDING_X, COUNT_PADDING_Y + COUNT_SPACING * 3)

            count_draw.text(
                ap_pos, "AP", fill=COUNT_FONT_COLOR, font=COUNT_FONT_CATEGORIES
            )
            count_draw.text(
                fc_pos, "FC", fill=COUNT_FONT_COLOR, font=COUNT_FONT_CATEGORIES
            )
            count_draw.text(
                clear_pos, "CLEAR", fill=COUNT_FONT_COLOR, font=COUNT_FONT_CATEGORIES
            )
            count_draw.text(
                all_pos, "ALL", fill=COUNT_FONT_COLOR, font=COUNT_FONT_CATEGORIES
            )

            count_draw.text(
                (count_width - COUNT_PADDING_X, ap_pos[1]),
                str(diff.ap_count),
                fill=COUNT_FONT_COLOR,
                font=COUNT_FONT_TEXT,
                anchor="ra",
            )
            count_draw.text(
                (count_width - COUNT_PADDING_X, fc_pos[1]),
                str(diff.fc_count),
                fill=COUNT_FONT_COLOR,
                font=COUNT_FONT_TEXT,
                anchor="ra",
            )
            count_draw.text(
                (count_width - COUNT_PADDING_X, clear_pos[1]),
                str(diff.clear_count),
                fill=COUNT_FONT_COLOR,
                font=COUNT_FONT_TEXT,
                anchor="ra",
            )
            count_draw.text(
                (count_width - COUNT_PADDING_X, all_pos[1]),
                str(diff.all_count),
                fill=COUNT_FONT_COLOR,
                font=COUNT_FONT_TEXT,
                anchor="ra",
            )

            data_img.alpha_composite(count_img, (CARD_WIDTH - count_width, 0))

            x_location = (
                CARD_GUTTER_WIDTH if i % 2 == 0 else CARD_WIDTH + CARD_GUTTER_WIDTH * 2
            )
            y_location = (
                HEADER_HEIGHT
                + SUB_HEADER_HEIGHT
                + CARD_GUTTER_HEIGHT
                + (i // 2) * (CARD_HEIGHT + CARD_GUTTER_HEIGHT)
            )
            new_im.alpha_composite(data_img, (x_location, y_location))

        obj = BytesIO()
        new_im.save(obj, "PNG")
        return obj

    return main(data)
